dep=['comps','it','mech','extc']
years=['FE','SE','TE','BE']
tags=[
    'it_Deep Learning',
'it_Machine Learning',
'it_Data Science',
'it_Big Data',
'it_2D & 3D Game Development',
'it_Augmented Reality, Virtual Reality and Mixed Reality',
'it_DevOps',
'it_Docker',
'it_OpenShift',
'it_Kubernetes',
'it_Cloud Servies & Technologies',
'it_Amazon Web Services',
'it_Google Cloud',
'it_OpenStack',
'it_Ansible',
'it_Front End Development',
'it_Server Side Development',
'it_Wordpress/ Joomla',
'it_MEAN Stack',
'it_Application Security',
'it_Network Security',
'it_Penetration Testing',
'it_Incident Management',
'it_Edge Computing',
'it_IoT Platform Management',
'it_Git Version Control',
'it_Python',
'it_C',
'it_Go',
'it_Ruby',
'it_JavaScript',
'it_TypeScript',
'it_Django',
'it_Flask',
'it_Frappé',
'it_ExpressJS',
'it_Angular',
'it_React',
'it_Tensorflow',
'it_Keras'
]
print(len(tags))